### ISSUE TITLE
Scheduler Invalid configuration

### ISSUE THREAD

**Issue by JohnnyPicnic** [jensrossbach/node-red-contrib-chronos#192]
**Describe the bug**
Scheduler node always showing invalid configuration. Screenshot of my setup below.

**Screenshots**
![2024-08-06_8-39-40](https://github.com/user-attachments/assets/9508426a-7f5f-474c-b6a1-05867ad4ca27)

**Context information**
Please complete the following information.
 - Platform & OS: windows
 - node-red-contrib-chronos version: 1.25.5
 - Node-RED version: 3.0.2
 - Node.js version:

**Additional information**
Add any other information about the problem here.

**Comment by jensrossbach** [comment]
Hi, can you hover with the mouse pointer over the little red triangle and tell me, what is written in the tooltip?

**Comment by JohnnyPicnic** [comment]
I did not know you that's there was some information hidden there. 
![image](https://github.com/user-attachments/assets/96a0a291-483a-416c-a114-a91f8b332e14)

**Comment by jensrossbach** [comment]
Seems that the function `RED.utils.validateTypedProperty`, which the chronos nodes are using since 1.25.5 to validate configured properties, has been added in Node-RED 3.1.1 earliest (and therefore it's not working for you as you use version 3.0.2). I need to investigate how to circumvent this (probably check if the function is available).

**Comment by JohnnyPicnic** [comment]
Ok thanks, I should probably update to 4.0 anyways.
