### ISSUE TITLE
wrong state with repeat module

### ISSUE THREAD

**Issue by mikhan253** [jensrossbach/node-red-contrib-chronos#193]
**Describe the bug**
repeat node somehow gets another value from other flows which are linked together.
as shown in the screenshot, true or false is injected into the repeat node with none set topic.
then on the output suddenly the topic name will be set to "wasserzukalt" which is another node on another flow.

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/4db998ee-03f8-45d9-95a9-772698de5b55)

**Context information**
Please complete the following information.
 - Platform & OS: linux-amd64, Artix Linux
 - node-red-contrib-chronos version: 1.25.5
 - Node-RED version: v4.0.5
 - Node.js version: 20.18.0

**Comment by jensrossbach** [comment]
The repeat node stores a reference to the incoming message and sends a clone of the stored reference except for one case: the initial sending of the message when the node is configured with "When message arrives on input" to "forward message" or "forced forward message". In this case, directly the stored reference is sent. If then the first receiving node (in your case "Wärmepumpe ThermaV Alive" modifies the message, it actually modifies the original message to which the stored reference is pointing and hence, subsequent repetitions contain these modifications.

To fix this behavior, I will change the code so that also in the initial forwarding case, a clone of the message is sent instead of the original message.

**Comment by jensrossbach** [comment]
Fixed with release [1.25.6](https://github.com/jensrossbach/node-red-contrib-chronos/releases/tag/v1.25.6).
