### ISSUE TITLE
Use Chronos Config to set date/time

### ISSUE THREAD

**Issue by ErwinAnwyhere365** [jensrossbach/node-red-contrib-chronos#82]
As discussed in on our other topic I would like to raise a feature request to use the chronos config to set the date time in the node itself. In this way you will we able to use the configured chronos locations date time in stead of the Node Red Instance time.

**Comment by jensrossbach** [comment]
Please note that I will implement only the possibility to **manually** configure the time zone in the configuration node (e.g., via a text field where you can enter the IANA name of the time zone). A programmatic calculation of the time zone based on the geographical coordinates requires large databases which need to be updated regularly in order to guarantee accuracy. Also there are corner cases where coordinates do not match an exact time zone and therefore manual control would anyway be necessary. I don't think this small piece of convenience outweighs the disadvantages of a significantly increased package size due to a large database which in addition requires regular updates.

**Comment by jensrossbach** [comment]
Implemented with release v1.17.0.
